[package]
name = "json-header-map"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
tako-rs = { path = "../.." }
tokio = { version = "1.45.1", features = ["full"] }
